org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:ActiveProcessorCount=2
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.daemon=false
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true

android.experimental.enableScreenshotTest=true
android.compose.screenshot.maxHeapSize=768m
