import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { renderToStaticMarkup } from 'react-dom/server'
import { MemoryRouter } from 'react-router-dom'
const source = (name: string) => readFileSync(new URL(`../src/renderer/src/${name}`, import.meta.url), 'utf8')
const ai = source('pages/settings/AISettings.tsx')
assert.doesNotMatch(ai, /<SettingsSection title="ChatGPT"|testCodexConnection/, 'writing credentials no longer duplicate the ChatGPT connection section')
assert.match(ai, /title="Groq"[\s\S]{0,180}SettingsProviderIcon provider="groq"/)
assert.match(ai, /testGroqConnection/); assert.match(ai, /testGeminiConnection/)
assert.match(ai, /confirmClear: true/)
const gemini = source('assets/provider-logos/gemini.svg')
assert.doesNotMatch(gemini, /floodOpacity=/, 'standalone SVG attributes are not JSX props')
assert.equal((gemini.match(/flood-opacity="0"/g) || []).length, 7)
assert.match(source('assets/provider-logos/groq.svg'), /<svg[\s\S]*viewBox=/)
assert.match(source('pages/settings/SettingsProviderIcon.tsx'), /provider === 'groq'/)
assert.match(source('pages/settings/SettingsChoiceDropdown.tsx'), /matchTriggerWidth/)
assert.doesNotMatch(source('pages/settings/SettingsChoiceDropdown.tsx'), /menuWidth=\{208\}/)
const { resolveFileActionsMenuWidth } = await import('../src/renderer/src/components/ui/file-actions-menu-layout')
assert.equal(resolveFileActionsMenuWidth(208, 176, 1200, true), 176)
assert.equal(resolveFileActionsMenuWidth(208, 310, 1200, true), 310)
assert.equal(resolveFileActionsMenuWidth(208, 310, 260, true), 236, 'matched menus remain viewport bounded')
assert.equal(resolveFileActionsMenuWidth(208, 176, 1200, false), 208, 'unrelated action menus retain explicit widths')
assert.equal(resolveFileActionsMenuWidth(208, 0, 1200, true), 208)
assert.doesNotMatch(source('pages/settings/AppearanceSettings.tsx'), /!max-w-\[800px\]/)
const { SettingsPageFrame } = await import('../src/renderer/src/pages/settings/SettingsPageFrame')
const frame = renderToStaticMarkup(<MemoryRouter><SettingsPageFrame><span>Content</span></SettingsPageFrame></MemoryRouter>)
assert.match(frame, /zyra-settings-page-container/); assert.match(frame, /max-w-\[760px\]/)
assert.match(source('pages/settings/settings-layout.tsx'), /<SettingsPageFrame/)
assert.match(source('pages/settings/SettingsShell.tsx').split('function SettingsRouteFallback')[1].split('export default')[0], /<SettingsPageFrame/)
console.log('Settings consistency: correct SVG attributes/marks, scoped provider removal, trigger-matched widths and shared loaded/loading page frame: ok')
