import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const source = (path: string) => readFileSync(new URL(`../src/renderer/src/${path}`, import.meta.url), 'utf8')
assert.match(source('components/layout/TitleBar.tsx'), /<AccessoriesMenu/, 'Zyra menu exposes the Accessories submenu')
const menu = source('components/layout/AccessoriesMenu.tsx')
for (const label of ['Browser', 'Incognito Browser', 'Terminal', 'File Explorer']) assert.ok(menu.includes(label))
const submenu = source('components/layout/AppSubmenu.tsx')
assert.match(submenu, /onPointerEnter/)
assert.match(submenu, /ArrowRight/)
assert.match(submenu, /ArrowLeft/)
assert.match(submenu, /AnchoredNativeOverlay/)
assert.match(menu, /Voice Lab/)
assert.match(source('components/layout/TitleBar.tsx'), /icon: <SquarePen/)
assert.match(source('components/layout/TitleBar.tsx'), /<AppSubmenu label="View"/)
const host = source('components/ui/DesktopLinkHost.tsx')
assert.doesNotMatch(host, /<DesktopLinkBrowser/)
assert.match(host, /openAccessory\(\{ kind: 'browser'/)
assert.match(source('App.tsx'), /<AccessoryWindowPage/)
const page = source('pages/accessories/AccessoryWindowPage.tsx')
assert.match(page, /accessories\.getState\(\)/)
assert.match(page, /api\.onChanged/)
assert.doesNotMatch(page, /selectedSession|createAssistantChat|assistant\.createSession/)
const files = source('pages/accessories/AccessoryFiles.tsx')
const terminal = source('pages/accessories/AccessoryTerminal.tsx')
assert.match(files, /<AssistantFilesWorkspace/)
assert.match(files, /onPreviewOpenChange/)
assert.match(terminal, /<AssistantTerminalWorkspace/)
assert.match(terminal, /terminalOwner=\{\{ kind: 'accessory-window', workspaceId \}\}/, 'terminal scope and shutdown belong to the accessory window')
assert.doesNotMatch(terminal, /canonicalChatId|selectedSession/)
assert.match(page, /beforeunload/)
for (const path of ['components/layout/AccessoriesMenu.tsx', 'pages/accessories/AccessoryWindowPage.tsx', 'pages/accessories/AccessoryFiles.tsx', 'pages/accessories/AccessoryTerminal.tsx']) new Bun.Transpiler({ loader: 'tsx' }).transformSync(source(path))
console.log('Accessories UI: hover/keyboard entry, chat-independent window state, real workspaces, safe file close and link routing: ok')
