import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { isBrowserDevscopeBridgePath } from '../src/shared/browser-assistant-bridge'
import { classifyBrowserDownload } from '../src/shared/browser-download-guard'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const manager = read('../src/main/browser-download-service.ts')
const handlers = read('../src/main/ipc/handlers/browser-preview-handlers.ts')
const ipc = read('../src/main/ipc/handlers.ts')
const preload = read('../src/preload/adapters/projects-adapter.ts')
const popupPreload = read('../src/preload/adapters/browser-popup-adapter.ts')
const workspace = read('../src/renderer/src/pages/assistant/AssistantBrowserWorkspace.tsx')
const popup = read('../src/renderer/src/pages/assistant/AssistantBrowserPopupWindow.tsx')
const downloadsUi = read('../src/renderer/src/pages/assistant/AssistantBrowserDownloadsButton.tsx')
const downloadsPanel = read('../src/renderer/src/pages/assistant/AssistantBrowserDownloadsPanel.tsx')
const historyPanel = read('../src/renderer/src/pages/assistant/AssistantBrowserHistoryPanel.tsx')
const styles = read('../src/renderer/src/index.css')

assert.equal(isBrowserDevscopeBridgePath(['listBrowserDownloads']), false, 'remote pages cannot inspect Zyra download history')
assert.equal(isBrowserDevscopeBridgePath(['actOnBrowserDownload']), false, 'remote pages cannot operate on downloaded files')
assert.equal(isBrowserDevscopeBridgePath(['getBrowserDownloadPreviewTarget']), false, 'remote pages cannot resolve download filesystem paths')
assert.equal(isBrowserDevscopeBridgePath(['listBrowserDownloadsFolder']), false, 'remote pages cannot enumerate the operating-system Downloads folder')
assert.equal(isBrowserDevscopeBridgePath(['actOnBrowserDownloadsFolderEntry']), false, 'remote pages cannot operate on files in the operating-system Downloads folder')
assert.match(manager, /app\.getPath\('downloads'\)/, 'Browser downloads use the operating-system Downloads folder')
assert.match(manager, /item\.setSavePath\(savePath\)/, 'main assigns a collision-safe path without exposing it to the page')
assert.match(manager, /reservedPaths/, 'concurrent downloads cannot overwrite each other')
assert.match(manager, /DOWNLOAD_HISTORY_LIMIT = 200/, 'download history remains bounded')
assert.match(manager, /DOWNLOAD_FOLDER_ENTRY_LIMIT = 200/, 'the Downloads-folder view remains bounded')
assert.match(manager, /DOWNLOAD_FOLDER_SCAN_LIMIT = 1_000/, 'folder metadata work has a hard scan bound')
assert.match(manager, /downloads-v1\.json/, 'Zyra-owned download history persists separately from website data')
assert.match(manager, /isPathInside\(this\.downloadsRoot, record\.savePath\)/, 'open, reveal, preview, and deletion remain confined to the Downloads folder')
assert.match(manager, /previewTarget\(id: string\): BrowserDownloadPreviewTarget/, 'trusted Browser chrome can resolve one existing download for Zyra preview')
assert.match(manager, /await unlink\(record\.savePath\)/, 'confirmed deletion removes the actual downloaded file')
assert.match(manager, /DOWNLOAD_PROGRESS_BROADCAST_MS = 100/, 'progress event volume is bounded')
assert.match(manager, /sourceContents\.downloadURL\(retry\.url\)/, 'retry keeps Chromium security checks by using the originating guest')
assert.match(manager, /WINDOWS_INTERNET_ZONE_MARK = '\[ZoneTransfer\]\\r\\nZoneId=3\\r\\n'/, 'Windows downloads receive Internet-zone metadata')
assert.match(manager, /writeFile\(`\$\{record\.savePath\}:Zone\.Identifier`/, 'Mark of the Web is written to the downloaded file alternate stream')
assert.match(manager, /pendingOpenConfirmations/, 'dangerous-file opens use a bounded main-process confirmation challenge')
assert.match(manager, /pendingFolderOpenConfirmations/, 'dangerous files discovered in the Downloads folder use their own bounded confirmation challenge')
assert.match(manager, /basename\(filename\) !== filename/, 'folder actions accept only direct Downloads-folder filenames')
assert.match(manager, /!fileStats\.isFile\(\) \|\| fileStats\.isSymbolicLink\(\)/, 'folder actions reject directories and symbolic links')
assert.match(manager, /classifyBrowserDownload\(action\.filename, ''\)/, 'folder files receive the same executable risk classification before open')
assert.match(manager, /action\.type === 'confirm-open'/, 'only the explicit second open action can consume the confirmation challenge')
assert.match(manager, /app\.getFileIcon\(record\.savePath, \{ size: 'normal' \}\)/, 'main extracts the real operating-system file icon after the file exists')
assert.match(manager, /icon\.toDataURL\(\)/, 'the extracted icon crosses IPC as inert image data')
const doneHandler = manager.slice(manager.indexOf("item.once('done'"), manager.indexOf('private async finalizeCompletedDownload'))
assert.doesNotMatch(doneHandler, /shell\.openPath/, 'completed downloads are never opened automatically')
assert.doesNotMatch(handlers, /browserSession\.on\('will-download', \(event\) => event\.preventDefault\(\)\)/, 'the old blanket download denial is removed')
assert.match(handlers, /attachSession\(browserSession, isAuthorizedBrowserPermissionTarget\)/, 'only registered Browser guests can initiate managed downloads')
assert.match(ipc, /BROWSER_DOWNLOADS_LIST_CHANNEL/, 'download history crosses typed IPC')
assert.match(ipc, /BROWSER_DOWNLOADS_PREVIEW_CHANNEL/, 'Open here resolves through dedicated main-owned IPC')
assert.match(ipc, /BROWSER_DOWNLOADS_FOLDER_LIST_CHANNEL/, 'bounded Downloads-folder listing crosses dedicated IPC')
assert.match(ipc, /BROWSER_DOWNLOADS_FOLDER_ACTION_CHANNEL/, 'bounded Downloads-folder actions cross dedicated IPC')
assert.match(preload, /onBrowserDownloadsChanged/, 'main Browser chrome receives bounded progress events')
assert.match(preload, /getBrowserDownloadPreviewTarget/, 'trusted main Browser chrome can request a path-confined preview target')
assert.match(preload, /listBrowserDownloadsFolder/, 'trusted Browser chrome can request the bounded folder view')
assert.match(preload, /actOnBrowserDownloadsFolderEntry/, 'trusted Browser chrome can request a path-confined folder action')
assert.match(popupPreload, /onDownloadsChanged/, 'popup chrome shares the same main-owned download manager')
assert.match(workspace, /<AssistantBrowserDownloadsButton[\s\S]{0,160}api=\{browserDownloadsApi\}[\s\S]{0,120}onOpenHere=\{openDownloadHere\}/, 'the main Browser places downloads beside its address bar and opens supported files in its active Zyra window')
assert.match(workspace, /<AssistantBrowserDownloadsPanel[\s\S]*api=\{browserDownloadsApi\}/, 'the full Downloads history is a separate surface backed by the same trusted download service')
assert.match(workspace, /<span>History<\/span>[\s\S]*<span>Downloads<\/span>/, 'the Browser menu opens both full history surfaces')
assert.doesNotMatch(workspace, /Local Browser profile|Website sign-ins persist on this device/, 'the Browser menu does not carry a verbose profile explanation')
assert.match(workspace, /BROWSER_MENU_ROW_CLASS/, 'the Browser menu uses one consistent active-action text hierarchy')
assert.match(workspace, /w-64 rounded-\[7px\]/, 'the Browser menu uses restrained outer corners')
assert.match(popup, /<AssistantBrowserDownloadsButton api=\{browserDownloadsApi\}/, 'popup Browser chrome exposes the same downloads flyout')
assert.match(downloadsUi, /DownloadProgressRing/, 'the toolbar icon renders determinate or indeterminate progress')
assert.match(downloadsUi, /<DownloadFileIcon download=\{download\} size=\{16\}/, 'download rows prefer the real operating-system icon when one is available')
assert.match(downloadsUi, /<FileEntryIcon pathValue=\{download\.filename\} kind="file"/, 'the Material file icon remains the bounded fallback')
assert.match(downloadsUi, /Pause download/, 'active downloads can pause')
assert.match(downloadsUi, /Resume download/, 'resumable downloads can continue')
assert.match(downloadsUi, /Cancel download/, 'active downloads can cancel')
assert.match(downloadsUi, /title="Delete downloaded file\?"/, 'file deletion requires Zyra’s destructive confirmation')
assert.match(downloadsUi, /<Ellipsis size=\{12\}/, 'terminal download actions collapse into one three-dot menu')
assert.match(downloadsUi, /<FileSearch2 size=\{12\} \/><span>Open here<\/span>/, 'previewable files offer Open here with the file-preview icon')
assert.match(downloadsUi, /<span>Show in folder<\/span>/, 'the item menu retains Show in folder')
assert.match(downloadsUi, /<span>Open<\/span>/, 'the item menu retains operating-system Open')
assert.match(downloadsUi, /title="This file can run code"/, 'dangerous files receive a direct warning before operating-system open')
assert.match(downloadsUi, /type: 'confirm-open'/, 'the warning confirmation consumes the main-process challenge')
assert.match(downloadsUi, /confirmLabel="Open anyway"/, 'the dangerous action stays explicit')
assert.match(downloadsUi, /void act\(\{ type: 'delete', id \}\)/, 'confirmation invokes the main-owned delete action')
assert.doesNotMatch(downloadsUi, /Remove from downloads/, 'the old history-only remove control is gone')
assert.match(downloadsUi, /Open Downloads folder/, 'users can inspect the complete OS Downloads folder from the header')
assert.doesNotMatch(downloadsUi, /Saved to your Downloads folder/, 'the compact flyout has no explanatory subtitle')
assert.doesNotMatch(downloadsUi, /<footer/, 'the compact flyout has no redundant footer')
assert.match(downloadsUi, /w-\[306px\]/, 'the toolbar keeps its compact Downloads flyout')
assert.match(downloadsUi, /pendingOpen\.download\.sourceOrigin/, 'the dangerous-file confirmation identifies the source')
assert.match(downloadsPanel, /role="dialog" aria-modal="true"/, 'the full Downloads history uses the focused History-panel pattern')
assert.match(downloadsPanel, /placeholder=\{view === 'folder' \? 'Search Downloads folder' : 'Search Zyra downloads'\}/, 'both full download views are searchable with source-specific copy')
assert.match(downloadsPanel, /useState<'zyra' \| 'folder'>\('zyra'\)/, 'the full panel defaults to Zyra-managed download history')
assert.match(downloadsPanel, /role="tablist" aria-label="Downloads source"[\s\S]*>Zyra<\/button>[\s\S]*>Folder<\/button>/, 'the full panel exposes a compact Zyra and Folder source toggle')
assert.match(downloadsPanel, /api\.listFolder\(\)/, 'the operating-system folder is read only when its view is requested')
assert.match(downloadsPanel, /entry\.systemIconDataUrl/, 'the Folder view uses the operating-system icon when main provides one')
assert.match(downloadsPanel, /type: 'confirm-open', filename: entry\.filename, token/, 'dangerous Folder-view opens consume the main-process confirmation challenge')
assert.match(downloadsPanel, /type: 'clear-history'/, 'full download history can be cleared without deleting downloaded files')
assert.match(downloadsPanel, /download\.systemIconDataUrl/, 'the full history also uses the operating-system file icon when available')
assert.match(downloadsPanel, /Open Downloads folder/, 'the full history opens the operating-system Downloads folder')
assert.match(downloadsPanel, /closing \? 'translate-x-\[calc\(100%\+16px\)\]'/, 'the Downloads panel animates out before it unmounts')
assert.match(historyPanel, /closing \? 'translate-x-\[calc\(100%\+16px\)\]'/, 'the History panel animates out before it unmounts')
assert.match(styles, /browser-download-button-arrive/, 'a new download receives a restrained toolbar arrival animation')
assert.match(styles, /prefers-reduced-motion: reduce[\s\S]*browser-download-progress-indeterminate/, 'download motion respects reduced-motion preferences')

for (const extension of ['exe', 'msi', 'bat', 'cmd', 'ps1', 'scr', 'js']) {
    assert.equal(classifyBrowserDownload(`payload.${extension}`, 'https://downloads.example'), 'dangerous', `.${extension} downloads are classified as dangerous`)
}
assert.equal(classifyBrowserDownload('project.ts', 'https://github.com'), 'normal', 'normal source files remain quiet')
assert.equal(classifyBrowserDownload('manual.pdf', 'https://example.com'), 'normal', 'PDF downloads remain quiet')
assert.equal(classifyBrowserDownload('screenshot.png', 'https://example.com'), 'normal', 'image downloads remain quiet')
assert.equal(classifyBrowserDownload('bundle.zip', 'https://example.com'), 'archive', 'remote archives receive a caution state')
assert.equal(classifyBrowserDownload('dev-server.exe', 'http://localhost:3000'), 'normal', 'localhost downloads remain quiet')

console.log('Browser downloads contract: ok')
