import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const desktopRoot = path.resolve(scriptDirectory, '..')
const sharedSource = readFileSync(path.join(desktopRoot, 'src/shared/renderer-diagnostics.ts'), 'utf8')
const preloadSource = readFileSync(path.join(desktopRoot, 'src/preload/renderer-diagnostics.ts'), 'utf8')
const preloadEntrySource = readFileSync(path.join(desktopRoot, 'src/preload/index.ts'), 'utf8')
const recorderSource = readFileSync(path.join(desktopRoot, 'src/main/diagnostics/renderer-hang-recorder.ts'), 'utf8')
const mainSource = readFileSync(path.join(desktopRoot, 'src/main/index.ts'), 'utf8')
const serviceSource = readFileSync(path.join(desktopRoot, 'src/main/assistant/service.ts'), 'utf8')

assert.match(sharedSource, /RENDERER_DIAGNOSTIC_SIGNAL_CHANNEL = 'zyra:diagnostics:renderer-signal'/, 'renderer health uses one private typed IPC channel')
assert.match(preloadEntrySource, /installRendererDiagnostics\(\)[\s\S]*createDevScopeElectronAdapter\(\)/, 'diagnostics wrap IPC before renderer adapters capture invoke')
assert.match(preloadSource, /HEARTBEAT_INTERVAL_MS = 2_000/, 'renderer heartbeat remains low-frequency')
assert.match(preloadSource, /EVENT_LOOP_STALL_THRESHOLD_MS = 250/, 'renderer event-loop stalls are measured without frame-level polling')
assert.match(preloadSource, /PerformanceObserver[\s\S]*entryTypes: \['longtask'\]/, 'Chromium long tasks are captured after recovery')
assert.match(preloadSource, /entry\.startTime < visibleSince/, 'long tasks spanning a hidden or suspended renderer are excluded')
assert.match(preloadSource, /lastEventLoopSampleAt = now[\s\S]*visibleSince = document\.visibilityState === 'visible'/, 'visibility resumption resets the renderer stall baseline')
assert.match(preloadSource, /data-zyra-diagnostic-surface[\s\S]*sourceCharacters[\s\S]*itemCount/, 'heartbeats identify the active bounded rendering surface without file content')
assert.match(preloadSource, /document\.visibilityState === 'visible'/, 'background timer throttling cannot create false renderer stall reports')
assert.match(preloadSource, /safeIpcContext[\s\S]*ASSISTANT_IPC\.getHistoryPage[\s\S]*context\.direction/, 'history diagnostics retain safe thread and paging context')
assert.match(preloadSource, /devscope:browserView:command[\s\S]*context\.tabId[\s\S]*context\.operation/, 'Browser diagnostics identify safe tab and operation metadata without URLs')
assert.match(recorderSource, /'control-overlay'\]\.includes\(operation\)/, 'main diagnostics allow-list Browser operation names')
assert.equal(preloadSource.includes('prompt:'), false, 'diagnostics never persist prompt content')
assert.equal(preloadSource.includes('filePath:'), false, 'diagnostics never persist file paths')

assert.match(recorderSource, /RECENT_EVENT_LIMIT = 80/, 'the in-memory diagnostic timeline is bounded')
assert.match(recorderSource, /ACTIVE_IPC_LIMIT = 64/, 'active IPC tracking is bounded')
assert.match(recorderSource, /REPORT_FILE_MAX_BYTES = 5 \* 1024 \* 1024/, 'incident files rotate at a bounded size')
assert.match(recorderSource, /HIGH_CPU_THRESHOLD_PERCENT = 4\.5[\s\S]*HIGH_CPU_CONSECUTIVE_SAMPLES = 3[\s\S]*CPU_PROFILE_DURATION_MS = 5_000/, 'CPU profiling starts only after sustained high renderer CPU and remains time-bounded')
assert.match(recorderSource, /now - state\.createdAt >= 20_000/, 'CPU profiling ignores ordinary renderer startup work')
assert.match(recorderSource, /CPU_PROFILE_RETAIN_COUNT = 3[\s\S]*\.endsWith\('\.cpuprofile'\)/, 'diagnostic CPU profiles have bounded retention')
assert.match(recorderSource, /Profiler\.start[\s\S]*Profiler\.stop[\s\S]*sustained-renderer-high-cpu/, 'a pathological responsive renderer yields an attributable Chromium CPU profile')
assert.match(recorderSource, /mode: 0o600/, 'incident reports are private to the local user')
assert.match(recorderSource, /const visible = state\.lastHeartbeat\?\.visibility === 'visible'[\s\S]{0,180}!owner\?\.isMinimized\(\)/, 'the heartbeat watchdog ignores hidden and minimized renderers')
assert.match(recorderSource, /persistIncident\('renderer-unresponsive'/, 'Electron unresponsive events persist incident evidence')
assert.match(recorderSource, /persistIncident\('visible-renderer-heartbeat-stalled'/, 'missed visible heartbeats provide an independent hang detector')
assert.match(recorderSource, /persistIncident\('main-event-loop-stall-recovered'/, 'main-process stalls are captured after the event loop recovers')
assert.match(recorderSource, /rendererHealthByWindow: \[\.\.\.states\.values\(\)\][\s\S]*activeIpc:[\s\S]*recentEvents: rendererState\.recentEvents\.slice\(-20\)/, 'main-process stalls retain bounded activity context from every renderer window')
assert.match(recorderSource, /signal\.state === 'ready'[\s\S]*state\.activeIpc\.clear\(\)[\s\S]*state\.recentEvents = \[\]/, 'renderer reloads cannot retain orphaned IPC or events from an obsolete page generation')
assert.match(recorderSource, /signal\.state === 'pagehide'[\s\S]*state\.activeIpc\.clear\(\)/, 'page teardown releases unfinished renderer IPC diagnostics')
assert.match(recorderSource, /processSnapshot\(\)[\s\S]*mainProcessMemory: process\.memoryUsage\(\)/, 'each incident includes all Electron process metrics and main memory')
assert.match(mainSource, /rendererHangRecorder\.captureRendererGone/, 'renderer process death persists the same evidence envelope')
assert.match(mainSource, /rendererHangRecorder\.captureChildProcessGone/, 'GPU and utility process deaths persist evidence')
assert.match(serviceSource, /getHangDiagnosticContext\(\)[\s\S]*messageCount:[\s\S]*activityCount:/, 'incident reports include bounded selected-chat context without transcript content')

console.log('Renderer hang diagnostics contract: ok')
