import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const files = read('../src/renderer/src/pages/assistant/AssistantFilesWorkspace.tsx')
const utilityHost = read('../src/renderer/src/pages/assistant/utility/AssistantUtilityWorkspaceHost.tsx')
const panel = read('../src/renderer/src/pages/assistant/AssistantDiffPanel.tsx')
const resources = read('../src/renderer/src/pages/assistant/AssistantResourcesWorkspace.tsx')
const resourceLibrary = read('../src/renderer/src/pages/assistant/AssistantResourcesLibrary.tsx')
const reviewLanding = read('../src/renderer/src/pages/assistant/AssistantReviewLanding.tsx')
const turnReview = read('../src/renderer/src/pages/assistant/AssistantTurnReview.tsx')
const previewInteractions = read('../src/renderer/src/components/ui/file-preview/useFilePreviewModalInteractions.tsx')
const previewLayout = read('../src/renderer/src/components/ui/file-preview/PreviewModalLayout.tsx')
const css = read('../src/renderer/src/index.css')

assert.match(files, /useFilePreview\(\)/, 'Files owns its preview state in every host')
assert.doesNotMatch(files, /shellMode=/, 'Files uses the same centered preview modal as the main window')
assert.match(files, /class FilesPreviewBoundary/, 'a preview failure cannot clear the entire Files workspace')
assert.match(files, /Back to files/, 'a failed preview has an explicit recovery path')
assert.match(files, /onOpenLinkedPreviewInNewTab=\{preview\.openPreviewInNewTab\}/, 'file subtabs remain real in the centered preview modal')
assert.doesNotMatch(previewLayout, /shellMode === 'embedded'/, 'the obsolete split-pane preview shell is removed')
assert.match(panel, /filesOpen[\s\S]*<AssistantFilesWorkspace projectPath=\{projectPath\} active=/, 'the main docked Inspector retains Files and its subtabs while another outer tab is selected')
assert.match(utilityHost, /<AssistantFilesWorkspace projectPath=\{tab\.path \|\| tab\.projectPath \|\| null\} active=\{active\}/, 'independent windows use the same active-aware Files workspace')
assert.doesNotMatch(previewInteractions, /useNavigate/, 'Router-free workspace windows cannot crash when a file opens')
assert.match(files, /active && preview\.previewFile/, 'hidden Files previews retain state without escaping their inactive outer tab')
assert.doesNotMatch(css, /assistant-files-workspace\[data-preview-open=/, 'Files no longer reserves a responsive split pane for previews')
assert.doesNotMatch(files, /Select a file to preview/, 'Files uses its full surface behind the centered preview modal')

assert.match(resources, /assistant-resources-workspace/, 'Resources owns a responsive container')
assert.doesNotMatch(resources, /min-w-\[700px\]/, 'narrow Resources does not force a desktop table width')
assert.match(css, /@container assistant-resources-workspace \(max-width: 419px\)/, 'Resources removes secondary columns at the narrowest dock width')
assert.match(css, /@container assistant-resources-workspace \(min-width: 680px\)/, 'Resources restores its complete metadata table when space permits')
assert.match(css, /@container assistant-resources-workspace \(min-width: 1080px\)/, 'wide Resources devotes its extra space to identity and provenance')
assert.match(resources, /<AssistantResourcesLibrary/, 'full-screen Resources switches to the dedicated Library and Inspector surface')
assert.match(resourceLibrary, /usePreviewVirtualWindow/, 'the full-screen resource library virtualizes visual rows')
assert.match(resourceLibrary, /aria-label="Resource filters"/, 'wide Resources exposes the selected type, source, and turn filter rail')
assert.match(resourceLibrary, /aria-label="Selected resource details"/, 'selection opens the dedicated resource inspector')
assert.match(resourceLibrary, /Provenance/, 'the inspector keeps originating turn context visible')

assert.match(reviewLanding, /assistant-review-landing/, 'Review landing owns a responsive container')
assert.doesNotMatch(reviewLanding, /AssistantReviewWideIndex/, 'Review keeps the original turn index and opens the complete review directly')
assert.match(css, /@container assistant-review-landing \(max-width: 539px\)/, 'narrow Review turns stack files beneath conversation context')
assert.doesNotMatch(turnReview, /TURN_REVIEW_THREE_PANE/, 'Review keeps conversation and changed files stacked in the original rail')
assert.doesNotMatch(css, /@container turn-review-root \(min-width: 1050px\)/, 'wide Review does not split changed files into a separate middle pane')

console.log('Assistant responsive workspace contract: ok')
