import assert from 'node:assert/strict'
import { buildUsageSummary, usageWindow } from '../src/shared/assistant/usage-summary'
import type { AssistantSessionTurnUsageEntry } from '../src/shared/assistant/contracts'
const now = new Date('2026-09-17T12:00:00Z')
const turn = (patch: Partial<AssistantSessionTurnUsageEntry> = {}): AssistantSessionTurnUsageEntry => ({ id:'a', sessionId:'session', threadId:'thread', model:'anthropic/claude-sonnet', state:'completed', requestedAt:'2026-09-17T08:00:00Z', startedAt:null, completedAt:null, assistantMessageId:null, updatedAt:'2026-09-17T08:01:00Z', usage:{inputTokens:100, outputTokens:25, cachedInputTokens:50, cacheWriteTokens:10, totalTokens:999999, reasoningOutputTokens:20, costUsd:.03}, ...patch })
const summarize = (turns: AssistantSessionTurnUsageEntry[], timeZone='UTC') => buildUsageSummary(turns,{days:7,timeZone},now)
const result = summarize([turn()])
assert.equal(result.totals.tokens,185,'input + output + caches, never context size or double-counted reasoning')
assert.equal(result.totals.costUsd,.03)
assert.equal(result.models[0].provider,'anthropic')
assert.equal(result.daily.length,7)
assert.equal(result.daily[0].date,'2026-09-11')
assert.equal(result.daily[0].tokens,0)
assert.equal(result.daily[6].tokens,185)
assert.equal(summarize([turn({model:'gpt-5',usage:{inputTokens:100,cachedInputTokens:50,outputTokens:25}})]).totals.tokens,125,'legacy Codex input includes cached tokens')
assert.equal(summarize([turn({usage:{inputTokens:100,cachedInputTokens:50,outputTokens:25,inputIncludesCachedTokens:true}})]).totals.tokens,125,'explicit input convention wins')
assert.equal(summarize([turn(),turn()]).totals.turns,1,'replays deduplicated')
assert.equal(summarize([turn(),turn({updatedAt:'2026-09-17T09:00:00Z',usage:{inputTokens:200}})]).totals.tokens,200,'latest usage wins')
assert.equal(summarize([turn({usage:null})]).totals.meteredTurns,0)
assert.equal(summarize([turn({usage:{inputTokens:0,outputTokens:0,costUsd:0}})]).totals.pricedTurns,1,'reported zero is available')
assert.equal(summarize([turn({usage:{totalTokens:900,sessionCostUsd:30}})]).totals.tokens,0)
assert.equal(summarize([turn({usage:{sessionCostUsd:30}})]).totals.pricedTurns,0,'cumulative cost is never added per turn')
assert.equal(summarize([turn({usage:{inputTokens:-1,outputTokens:NaN,costUsd:Infinity}})]).totals.tokens,0)
assert.equal(summarize([turn({requestedAt:'2026-09-10T23:59:59Z'}),turn({requestedAt:'2026-09-18T00:00:00Z'})]).totals.turns,0,'range bounds and future records excluded')
assert.equal(summarize([turn({requestedAt:'2026-09-10T22:00:00Z'})],'Africa/Dar_es_Salaam').totals.turns,1,'local midnight included')
assert.equal(summarize([turn({model:'custom/my/model'})]).models[0].model,'my/model')
assert.equal(summarize([turn({model:'legacy-unknown'})]).models[0].provider,'unknown')
assert.throws(()=>usageWindow({days:100 as any},now))
assert.throws(()=>usageWindow({timeZone:'not/a-zone'},now))
assert.equal(buildUsageSummary([],{days:90,timeZone:'America/New_York'},new Date('2026-11-05T12:00:00Z')).daily.length,90,'DST preserves calendar days')
console.log('Usage aggregation: 23 assertions passed.')
