import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { resolveBrowserWindowOpenIntent } from '../src/main/browser-window-open-policy'
import { resolveBrowserShortcut } from '../src/shared/browser-shortcuts'
import { addAssistantBrowserTab, createAssistantBrowserWorkspaceState, normalizeAssistantBrowserWorkspaceState } from '../src/renderer/src/pages/assistant/assistant-browser-workspace-state'
import { sanitizeBrowserPersistentUrl } from '../src/shared/browser-url-sanitization'

assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'foreground-tab' }), { kind: 'tab', activate: true })
assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'background-tab' }), { kind: 'tab', activate: false })
assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'new-window' }), { kind: 'popup' })
assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'default', frameName: 'oauth-login' }), { kind: 'popup' })
assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'default', features: 'width=520,height=700' }), { kind: 'popup' })
assert.deepEqual(resolveBrowserWindowOpenIntent({ url: 'https://example.com', disposition: 'default', postBody: {} }), { kind: 'popup' })
assert.deepEqual(resolveBrowserWindowOpenIntent({
    url: 'https://mail.google.com/mail/u/0/popout?ver=1&search=inbox&th=%23thread-f%3A123',
    disposition: 'foreground-tab'
}), { kind: 'popup' }, 'Gmail popouts retain window.opener even when Ctrl-click reports a foreground-tab disposition')
assert.deepEqual(resolveBrowserWindowOpenIntent({
    url: 'https://mail.google.com/mail/u/0/#inbox/thread-id',
    disposition: 'foreground-tab'
}), { kind: 'tab', activate: true }, 'ordinary Gmail destinations still use integrated Browser tabs')

const windows = 'win32' as const
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 't', control: true }, windows), { type: 'new-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 't', control: true, shift: true }, windows), { type: 'reopen-closed-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'w', control: true }, windows), { type: 'close-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'l', control: true }, windows), { type: 'focus-address' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'r', control: true, shift: true }, windows), { type: 'reload', bypassCache: true })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'Tab', control: true, shift: true }, windows), { type: 'previous-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'PageDown', control: true }, windows), { type: 'next-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: '1', control: true }, windows), { type: 'select-tab', index: 0 })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: '9', control: true }, windows), { type: 'select-tab', index: 'last' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'ArrowLeft', alt: true }, windows), { type: 'back' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'ArrowRight', alt: true }, windows), { type: 'forward' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'F11' }, windows), { type: 'toggle-fullscreen' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 't' }, windows), null)
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 't', meta: true }, 'darwin'), { type: 'new-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: ']', meta: true }, 'darwin'), { type: 'forward' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'Tab', control: true }, 'darwin'), { type: 'next-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'Tab', control: true, shift: true }, 'darwin'), { type: 'previous-tab' })
assert.deepEqual(resolveBrowserShortcut({ type: 'keyDown', key: 'Tab', meta: true }, 'darwin'), null, 'Command+Tab remains available to macOS application switching')

assert.equal(sanitizeBrowserPersistentUrl('https://user:pass@example.com/callback?code=secret&safe=1#token'), 'https://example.com/callback')
assert.equal(sanitizeBrowserPersistentUrl('https://example.com/login?ticket=secret&nonce=secret&otp=123456&redirect_url=https%3A%2F%2Fuser%3Apass%40target.example&return_url=https%3A%2F%2Ftarget.example%3Ftoken%3Dsecret&safe=1'), 'https://example.com/login', 'authentication routes drop their complete provider query rather than chasing individual secret aliases')
assert.equal(sanitizeBrowserPersistentUrl('https://accounts.google.com/signin/oauth/consent?client_id=public-client&part=provider-state&rapt=one-time-proof&flowName=OAuthFlow'), 'https://accounts.google.com/signin/oauth/consent', 'provider-specific authentication companions cannot survive URL persistence')
const restoredSensitiveWorkspace = normalizeAssistantBrowserWorkspaceState({ version: 1, activeTabId: 'browser:sensitive', splitTabId: null, tabs: [{ id: 'browser:sensitive', url: 'https://example.com/callback?oauth_token=secret&safe=1#fragment', title: '654321 - login code - person@example.com' }] })
assert.equal(restoredSensitiveWorkspace.tabs[0]?.url, 'https://example.com/callback', 'workspace restoration strips the complete authentication query before reuse')
assert.equal(restoredSensitiveWorkspace.tabs[0]?.title, 'example.com', 'workspace restoration strips authentication codes and account labels from persisted titles')
const restoredSamlWorkspace = normalizeAssistantBrowserWorkspaceState({ version: 1, activeTabId: 'browser:saml', splitTabId: null, tabs: [{ id: 'browser:saml', url: 'https://app.example/finish?SAMLResponse=encoded-assertion', title: '987654 - access for account@example.com' }] })
assert.equal(restoredSamlWorkspace.tabs[0]?.url, 'https://app.example/finish')
assert.equal(restoredSamlWorkspace.tabs[0]?.title, 'app.example', 'query-only authentication metadata cannot persist through a workspace migration')

const initial = createAssistantBrowserWorkspaceState('browser:initial')
const background = addAssistantBrowserTab(initial, 'browser:background', 'https://example.com', false)
assert.equal(background.activeTabId, 'browser:initial', 'background tabs do not steal selection')
assert.equal(background.tabs.at(-1)?.url, 'https://example.com')
const foreground = addAssistantBrowserTab(background, 'browser:foreground', 'https://example.org')
assert.equal(foreground.activeTabId, 'browser:foreground')

const desktopRoot = path.resolve(import.meta.dirname, '..')
const mainSource = readFileSync(path.join(desktopRoot, 'src/main/index.ts'), 'utf8')
const hangRecorderSource = readFileSync(path.join(desktopRoot, 'src/main/diagnostics/renderer-hang-recorder.ts'), 'utf8')
const popupManagerSource = readFileSync(path.join(desktopRoot, 'src/main/browser-popup-manager.ts'), 'utf8')
const browserViewManagerSource = readFileSync(path.join(desktopRoot, 'src/main/browser-view-manager.ts'), 'utf8')
const popupComponentSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/pages/assistant/AssistantBrowserPopupWindow.tsx'), 'utf8')
const popupAdapterSource = readFileSync(path.join(desktopRoot, 'src/preload/adapters/browser-popup-adapter.ts'), 'utf8')
const popupPreloadSource = readFileSync(path.join(desktopRoot, 'src/preload/browser-popup.ts'), 'utf8')
const preloadEntrySource = readFileSync(path.join(desktopRoot, 'src/preload/index.ts'), 'utf8')
const appSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/App.tsx'), 'utf8')
const diffPanelSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/pages/assistant/AssistantDiffPanel.tsx'), 'utf8')
const viteConfigSource = readFileSync(path.join(desktopRoot, 'electron.vite.config.ts'), 'utf8')
const preloadSource = readFileSync(path.join(desktopRoot, 'src/preload/adapters/projects-adapter.ts'), 'utf8')
const browserHandlersSource = readFileSync(path.join(desktopRoot, 'src/main/ipc/handlers/browser-preview-handlers.ts'), 'utf8')
const browserDeveloperHandlersSource = readFileSync(path.join(desktopRoot, 'src/main/ipc/handlers/browser-preview-developer-handlers.ts'), 'utf8')
const workspaceSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/pages/assistant/AssistantBrowserWorkspace.tsx'), 'utf8')
const apiSource = readFileSync(path.join(desktopRoot, 'src/shared/contracts/devscope-api.ts'), 'utf8')

assert.match(mainSource, /web-contents-created[\s\S]*getType\(\) === 'webview'[\s\S]*action: 'deny'/, 'new webviews deny popups before their owner-specific policy is attached')
assert.match(mainSource, /web-contents-created[\s\S]*rendererHangRecorder\.attach\(contents\)/, 'every future webContents is attached to the bounded hang recorder')
assert.match(hangRecorderSource, /contents\.on\('unresponsive'[\s\S]*persistIncident\('renderer-unresponsive'/, 'future renderer hangs persist the exact webContents incident')
assert.match(hangRecorderSource, /processSnapshot\(\)[\s\S]*mainProcessMemory: process\.memoryUsage\(\)/, 'hang incidents include Electron process and main-process memory evidence')
assert.match(browserViewManagerSource, /trustedBrowserGuests\.register\(record\.ownerWindow\.webContents\.id, page\)[\s\S]*registerBrowserPermissionTarget\(page, record\.ownerWindow\.webContents\)[\s\S]*popupManager\.registerGuest\(record\.ownerWindow, page, page\.id\)/, 'main-owned page policy is installed before popup handling is delegated')
assert.match(popupManagerSource, /createWindow:[\s\S]*createPopup[\s\S]*new WebContentsView\(\{ webContents: suppliedContents \}\)/, 'opener-owned popup WebContents are adopted into Zyra chrome instead of being replaced')
assert.match(popupManagerSource, /manuallyLoad[\s\S]*rawContentType[\s\S]*safeContentType[\s\S]*postData: postBody\.data[\s\S]*Content-Type: \$\{contentType\}/, 'deferred background popup creation preserves bounded POST bodies and their original content type')
assert.doesNotMatch(popupManagerSource, /contentType === 'application\/x-www-form-urlencoded' \|\|/, 'deferred POST replay is not restricted to only two form content types')
assert.match(popupManagerSource, /\{1,70\}[\s\S]*multipart\/form-data'[\s\S]*!safeBoundary[\s\S]*multipart boundary is invalid[\s\S]*boundary="\$\{safeBoundary\}"/, 'deferred multipart POST requests enforce the MIME boundary limit and serialize a quoted boundary')
assert.match(popupManagerSource, /MAX_MANAGED_BROWSER_POPUPS = 4[\s\S]*managedCount\(ownerWindow\) >= MAX_MANAGED_BROWSER_POPUPS/, 'untrusted pages cannot create an unbounded popup process tree')
assert.match(popupManagerSource, /activateOnReady: details\.disposition !== 'background-tab'[\s\S]*showInactive\(\)/, 'Ctrl/Cmd-click popup windows remain discoverable without stealing foreground focus')
assert.match(popupManagerSource, /sourceGuestWebContentsId[\s\S]*registerContextMenu\(ownerWindow, pageContents, sourceGuestWebContentsId, shellWindow\)/, 'popup context-menu tab actions retain the owning guest identity')
assert.match(popupManagerSource, /hardenPopupWebPreferences[\s\S]*session: sourceContents\.session[\s\S]*sandbox: true[\s\S]*nodeIntegration: false[\s\S]*webSecurity: true/, 'managed popups explicitly share the persistent Browser session while preserving hardened page preferences')
assert.match(popupManagerSource, /suppliedContents\.session !== sourceContents\.session[\s\S]*session isolation could not be preserved/, 'a popup cannot silently switch away from the authenticated Browser profile')
assert.match(popupManagerSource, /before-input-event[\s\S]*resolveBrowserShortcut[\s\S]*BROWSER_PREVIEW_SHORTCUT_CHANNEL/, 'shortcuts from a focused popup page use the shared browser shortcut policy')
assert.match(popupManagerSource, /Open link in new tab[\s\S]*Open link in background tab[\s\S]*Copy link address/, 'link context menus provide standard foreground, background, and copy actions')
assert.match(popupManagerSource, /registerContextMenu\(ownerWindow, pageContents, sourceGuestWebContentsId, shellWindow\)[\s\S]*activeMenuWindow[\s\S]*popup\(\{ window: activeMenuWindow \}\)/, 'popup context menus anchor to the current page shell while preserving the opener tab identity')
assert.match(popupManagerSource, /recordGlobalBrowserHistory[\s\S]*scheduleGlobalBrowserProfileFlush/, 'popup navigation joins local history and durable Browser-profile flushing')
assert.match(popupManagerSource, /did-navigate-in-page[\s\S]*recordNavigation\(url, true\)/, 'main-frame popup SPA transitions create history visits')
assert.match(popupManagerSource, /isAuthenticationBrowserUrl\(url\)[\s\S]*title = popupFallbackTitle\(url\)/, 'authentication popup chrome and recovery lists do not expose provider codes through page titles')
assert.match(popupManagerSource, /onSourceDestroyed[\s\S]*removeListener\('destroyed', popup\.onSourceDestroyed\)/, 'closing popup windows removes opener lifecycle listeners instead of accumulating them')
assert.match(popupManagerSource, /try \{[\s\S]*createShellWindow[\s\S]*new WebContentsView[\s\S]*catch \(error\)[\s\S]*disposePopup\(popup, true\)[\s\S]*shellWindow.*destroy\(\)/, 'exceptional popup construction tears down both hosted contents and its hidden shell')
assert.match(mainSource, /createBrowserPopupShellWindow[\s\S]*try \{[\s\S]*new BrowserWindow[\s\S]*catch \(error\)[\s\S]*popupWindow\.destroy\(\)/, 'the popup shell factory cleans a partially configured native window before rethrowing')
assert.match(mainSource, /createBrowserPopupShellWindow[\s\S]*skipTaskbar: false[\s\S]*getWindowChromeOptions\(\)[\s\S]*\/browser-popup\//, 'popup shells are independently selectable top-level windows with the platform frame and trusted renderer route')
assert.doesNotMatch(mainSource, /createBrowserPopupShellWindow[\s\S]{0,500}parent: input\.ownerWindow/, 'popup shells are not hidden behind an owner-only taskbar relationship')
assert.match(appSource, /browserPopupWindow[\s\S]*AssistantBrowserPopupWindow/, 'the popup route renders dedicated lightweight Browser chrome')
assert.match(popupComponentSource, /Zyra[\s\S]*Browser address[\s\S]*Uses the shared Zyra Browser profile[\s\S]*Browser window menu/, 'popup chrome includes app framing, navigation, address, profile, and menu affordances')
assert.match(popupComponentSource, /resolveBrowserShortcut[\s\S]*type: 'shortcut', action/, 'popup chrome forwards the complete shared shortcut action whenever it owns keyboard focus')
assert.match(popupManagerSource, /command\.type === 'shortcut'[\s\S]*runPopupShortcut[\s\S]*bypassCache[\s\S]*reloadIgnoringCache[\s\S]*BROWSER_PREVIEW_SHORTCUT_CHANNEL[\s\S]*revealOwnerWindow\(popup\.ownerWindow\)/, 'popup shortcut routing preserves bypass reload and visibly applies tab creation/reopen/cycling/selection in the owner Browser')
assert.match(popupAdapterSource, /BROWSER_POPUP_GET_STATE_CHANNEL[\s\S]*BROWSER_POPUP_COMMAND_CHANNEL[\s\S]*BROWSER_POPUP_LIST_CHANNEL[\s\S]*BROWSER_POPUP_FOCUS_WINDOW_CHANNEL[\s\S]*BROWSER_POPUP_STATE_CHANGED_CHANNEL/, 'popup chrome and window recovery cross a narrow typed preload boundary')
assert.match(viteConfigSource, /format: 'cjs'[\s\S]*entryFileNames: '\[name\]\.cjs'/, 'sandboxed chrome builds one self-contained CommonJS preload')
assert.doesNotMatch(viteConfigSource, /'browser-popup':/, 'sandboxed preload bundling cannot leave a local shared chunk')
assert.match(mainSource, /preload: getPreloadPath\(\)[\s\S]*additionalArguments: \[BROWSER_POPUP_PRELOAD_ARGUMENT\]/, 'popup shells receive a main-owned reduced-capability preload role')
assert.match(preloadEntrySource, /process\.argv\.includes\(BROWSER_POPUP_PRELOAD_ARGUMENT\)[\s\S]*installBrowserPopupPreload\(\)/, 'the shared preload selects popup authority before exposing a bridge')
assert.match(popupPreloadSource, /createWindowAdapter[\s\S]*createBrowserPopupAdapter[\s\S]*DEVICE_PREFERENCES_IPC\.get[\s\S]*update: unavailable/, 'popup preload exposes only window controls, popup control, and read-only appearance preferences')
assert.doesNotMatch(popupPreloadSource, /createDevScopeElectronAdapter|agentControl|openInTerminal|readFileContent|DEVICE_SECRETS_IPC/, 'popup preload cannot reach desktop filesystem, terminal, agent-control, or secret IPC')
assert.match(popupManagerSource, /BROWSER_POPUP_LIST_CHANNEL[\s\S]*windows: this\.listWindows\(ownerWindow\)/, 'the owning Browser can enumerate its popup windows')
assert.match(popupManagerSource, /findByGuestId\(popup\.sourceGuestWebContentsId\)[\s\S]*ownerThreadId: sourceBinding\?\.ownerThreadId/, 'popup recovery entries retain their bound chat-thread scope')
assert.match(workspaceSource, /popup\.ownerThreadId === threadId/, 'each Browser workspace filters popup recovery to its own chat thread')
assert.match(workspaceSource, /if \(active && normalizedProjectPath\) void refreshLocalServers\(\)/, 'hidden Browser workspaces do not launch local-server scans')
assert.match(workspaceSource, /if \(active\) void reloadBrowserHistory\(\)/, 'hidden Browser workspaces defer supplementary history reads')
assert.match(workspaceSource, /if \(!active \|\| !config \|\| config\.protectedMedia\.ready/, 'hidden Browser workspaces pause protected-media polling')
assert.match(workspaceSource, /useEffect\(\(\) => \{\s*if \(!active\) return\s*const popupApi/, 'hidden Browser workspaces release popup-list subscriptions')
assert.match(diffPanelSource, /<AssistantBrowserWorkspace[\s\S]*key=\{browserWorkspaceKey\}[\s\S]*workspaceKey=\{browserWorkspaceKey\}/, 'switching chat workspaces remounts Browser state instead of re-persisting the prior chat guests')
assert.match(popupManagerSource, /BROWSER_POPUP_FOCUS_WINDOW_CHANNEL[\s\S]*isMinimized\(\)[\s\S]*restore\(\)[\s\S]*shellWindow\.focus\(\)/, 'the owning Browser can restore and focus a minimized popup window')
assert.match(popupManagerSource, /action\.type === 'focus-address'[\s\S]*once\('leave-full-screen', focusAddress\)[\s\S]*setFullScreen\(false\)/, 'Ctrl/Cmd+L exits popup fullscreen before moving focus into chrome')
assert.match(workspaceSource, /popupWindows\.length[\s\S]*Open windows[\s\S]*browserPopup\.focusWindow/, 'the main Browser menu exposes a visible recovery list for open popup windows')
assert.match(preloadSource, /onBrowserOpenTabRequested[\s\S]*BROWSER_PREVIEW_OPEN_TAB_REQUESTED_CHANNEL/, 'tab requests cross the typed preload')
assert.match(preloadSource, /onBrowserShortcut[\s\S]*BROWSER_PREVIEW_SHORTCUT_CHANNEL/, 'guest shortcuts cross the typed preload')
assert.match(workspaceSource, /onBrowserOpenTabRequested[\s\S]*const sessionMode =[\s\S]*createTab\(request\.url, \{ activate: request\.activate, sessionMode \}\)/, 'foreground and background dispositions inherit the source tab storage mode')
const browserSlotSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/pages/assistant/AssistantBrowserWebview.tsx'), 'utf8')
assert.match(browserSlotSource, /data-assistant-browser-view-slot/, 'the renderer exposes only a slot for the main-owned page')
assert.match(browserViewManagerSource, /popupManager\.registerGuest\(record\.ownerWindow, page, page\.id\)/, 'main-owned pages delegate window-open requests to the hardened popup policy')
assert.match(workspaceSource, /closedTabsRef[\s\S]*reopen-closed-tab/, 'closed tabs can be restored with the standard shortcut')
assert.match(workspaceSource, /const closedTab = closedTabsRef\.current\.at\(-1\)[\s\S]*ASSISTANT_BROWSER_TAB_LIMIT[\s\S]*closedTabsRef\.current\.pop\(\)/, 'a failed restore at the tab limit keeps the closed entry available')
assert.match(workspaceSource, /window\.addEventListener\('keydown', handleBrowserShortcut, true\)/, 'renderer-focused browser chrome uses the same shortcut policy')
assert.match(workspaceSource, /previousTabId !== tabId[\s\S]*webviewRefs\.current\.get\(previousTabId\)\?\.blur\(\)/, 'tab switches release keyboard focus from the hidden previous guest')
assert.match(workspaceSource, /fullscreenTab && fullscreenTab !== tabId[\s\S]*setFullScreen\(false\)/, 'switching away from a fullscreen tab restores the normal window and Browser shell')
assert.match(browserViewManagerSource, /input\.key === 'Escape' && record\.ownerWindow\.isFullScreen\(\)[\s\S]*record\.ownerWindow\.setFullScreen\(false\)/, 'guest-focused Escape exits Browser fullscreen')
assert.match(apiSource, /DevScopeBrowserOpenTabRequest[\s\S]*DevScopeBrowserShortcutEvent/, 'tab and shortcut events have shared contracts')
assert.match(workspaceSource, /onBrowserOpenTabRequested/, 'renderer owns main-requested tab creation')
const workspaceStateSource = readFileSync(path.join(desktopRoot, 'src/renderer/src/pages/assistant/assistant-browser-workspace-state.ts'), 'utf8')
assert.match(workspaceStateSource, /workspaceSnapshotForPersistence[\s\S]*sanitizeBrowserPersistentUrl[\s\S]*sanitizeStoredWorkspaceRecord[\s\S]*localStorage\.setItem/, 'all persisted workspace records are scrubbed during migration and every write')
assert.match(browserHandlersSource, /persist:zyra-browser-[\s\S]*cookies\.on\('changed'[\s\S]*scheduleGlobalBrowserProfileFlush/, 'login cookies stay in a persistent partition and schedule a durable flush')
assert.match(browserHandlersSource, /AUTOMATIC_BROWSER_PERMISSIONS = new Set\(\['fullscreen', 'mediaKeySystem', 'clipboard-sanitized-write'\]\)[\s\S]*setPermissionCheckHandler[\s\S]*isSecureBrowserClipboardUrl/, 'focused secure Browser pages can use the standard async copy API alongside fullscreen and DRM')
assert.doesNotMatch(browserHandlersSource, /AUTOMATIC_BROWSER_PERMISSIONS = new Set\([^)]*clipboard-read/, 'sites cannot silently read the user clipboard')
assert.match(browserHandlersSource, /permission === 'clipboard-sanitized-write'[\s\S]*webContents\.isFocused\(\)[\s\S]*isSecureBrowserClipboardUrl/, 'async copy is limited to the focused trusted guest on HTTPS or localhost')
assert.match(mainSource, /flushGlobalBrowserProfileStorage\(\)\.then[\s\S]*globalShortcut\.unregisterAll\(\)[\s\S]*disposeAssistantService/, 'clean shutdown persists Browser login state before tearing down recoverable services')
assert.match(browserDeveloperHandlersSource, /colorScheme === 'system'[\s\S]*\? \[\][\s\S]*prefers-color-scheme/, 'System appearance clears CDP media emulation instead of sending an invalid empty value')
assert.match(browserViewManagerSource, /enter-html-full-screen[\s\S]*setFullScreen\(true\)[\s\S]*leave-html-full-screen[\s\S]*setFullScreen\(false\)/, 'guest HTML fullscreen drives the native window lifecycle')
assert.match(workspaceSource, /fixed inset-0 z-\[1100\][\s\S]*data-browser-fullscreen=\{browserFullscreen[\s\S]*onFullscreenChange=\{handleFullscreenChange\}/, 'fullscreen media occupies the complete app viewport while preserving the guest')

console.log('Browser window-open and shortcut policy: ok')
