package dev.zyra.mobile

import dev.zyra.mobile.data.SessionView
import dev.zyra.mobile.data.TimelineReducer
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test

/** The JSON is generated by the real Node gateway projector and outbound batcher. */
class TimelineWireTest {
    private fun fixture() = javaClass.classLoader!!.getResourceAsStream("gateway-timeline.json")!!.bufferedReader().use { JSONObject(it.readText()) }
    private fun replay(initial: SessionView, frames: JSONArray): SessionView {
        var state = initial
        for (i in 0 until frames.length()) state = TimelineReducer.apply(state, frames.getJSONObject(i))
        return state
    }
    private fun verify(state: SessionView, expected: JSONObject) {
        assertEquals(expected.getInt("items"), state.items.size)
        assertEquals(expected.getLong("sequence"), state.sequence)
        assertEquals(expected.getString("text"), state.items.single { it.role == "assistant" }.text)
        assertEquals(expected.getString("reasoning"), state.items.single { it.role == "assistant" }.reasoning)
        assertEquals(expected.getString("tool"), state.items.single { it.kind == "tool" }.text)
        assertFalse(state.running)
    }
    @Test fun realGatewayFramesRenderSeparateReasoningReplyAndOneTool() {
        val fixture = fixture()
        verify(replay(SessionView("chat"), fixture.getJSONArray("frames")), fixture.getJSONObject("expected"))
    }
    @Test fun reconnectInsideARealCoalescedThinkingFrameDoesNotRepeatText() {
        val fixture = fixture()
        val checkpoint = replay(SessionView("chat"), fixture.getJSONArray("checkpoint"))
        assertEquals("Check ", checkpoint.items.single().reasoning)
        val cached = TimelineReducer.decode(TimelineReducer.encode(checkpoint))
        val result = replay(cached, fixture.getJSONArray("frames"))
        verify(result, fixture.getJSONObject("expected"))
        assertEquals(result, replay(result, fixture.getJSONArray("frames")))
    }
    @Test fun savedVoiceFramesReconcileTheLiveTranscriptWithoutDuplicates() {
        val state = replay(SessionView("chat"), fixture().getJSONArray("canonicalFrames"))
        assertEquals(1, state.items.size)
        assertEquals("A saved Voice reply.", state.items.single().text)
        assertEquals(42L, state.items.single().historyIndex)
        assertTrue(dev.zyra.mobile.voice.VoiceTimeline.pending(state.items, listOf(dev.zyra.mobile.voice.VoiceTranscript("live", "assistant", "A saved Voice reply.", providerId = "voice-provider"))).isEmpty())
    }
}
