import { randomBytes } from 'node:crypto'
import { mountBrowserRecordingOverlay } from './browser-recording-overlay-client'

export function buildBrowserRecordingOverlayDocument(): string {
    const nonce = randomBytes(18).toString('base64')
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; base-uri 'none'; form-action 'none'; frame-src 'none'">
<style nonce="${nonce}">
:root{color-scheme:dark;--background:#252525;--foreground:#eeeeee;--muted:#aaaaaa;--accent:#ee9944;--border:#ffffff1a;font:12px/1.4 system-ui,-apple-system,'Segoe UI',sans-serif;color:var(--foreground)}
*{box-sizing:border-box}html,body{margin:0;background:transparent;overflow:hidden}body{padding:8px}button{font:inherit;color:inherit;border:0;background:transparent;cursor:pointer;white-space:nowrap}button:disabled{cursor:default;opacity:.42}button:focus-visible{outline:2px solid var(--accent);outline-offset:1px}button:hover:enabled{background:color-mix(in srgb,var(--foreground) 8%,transparent)}[hidden]{display:none!important}
#recorder{width:100%;border:1px solid var(--border);border-radius:12px;background:var(--background);box-shadow:0 3px 12px #0003;overflow:hidden;animation:arrive 260ms cubic-bezier(.22,1,.36,1) both}
#toolbar{display:flex;align-items:center;gap:3px;min-height:44px;padding:5px 7px}#clock{display:flex;align-items:center;gap:7px;padding:0 7px 0 4px;font-variant-numeric:tabular-nums;white-space:nowrap;min-width:64px}#indicator{width:7px;height:7px;flex:none;background:#f16464;border-radius:50%}#recorder[data-status=paused] #indicator{background:var(--muted)}#recorder[data-status=saved] #indicator{background:var(--accent)}#recorder[data-status=starting] #indicator,#recorder[data-status=stopping] #indicator{animation:breathe 1600ms ease-in-out infinite}
.control{height:30px;padding:0 9px;border-radius:6px;font-size:11px;display:inline-flex;align-items:center;justify-content:center;gap:5px}.control[data-selected=true]{color:var(--accent)}#stop{color:#f37b7b}#stop-mark{width:8px;height:8px;border-radius:2px;background:currentColor}#pause-mark{width:8px;height:10px;border-inline:2px solid currentColor}#pause[data-action=resume] #pause-mark{height:0;width:0;border:0;border-top:5px solid transparent;border-bottom:5px solid transparent;border-left:8px solid currentColor}.spacer{flex:1;min-width:0}.divider{width:1px;height:17px;background:var(--border);margin:0 3px}.chevron{width:5px;height:5px;border-right:1px solid currentColor;border-bottom:1px solid currentColor;transform:rotate(45deg);margin-top:-3px;opacity:.65}
#message{margin:0;padding:0 12px 10px;color:var(--muted);font-size:11px;overflow-wrap:anywhere;max-height:82px;overflow-y:auto}#message[data-error=true]{color:#ef9393}#saved-actions{display:flex;align-items:center;gap:4px;padding:0 7px 7px}#saved-actions .control:first-child{color:var(--accent)}#menu{border-top:1px solid var(--border);padding:7px;transform-origin:top center}#menu-title{margin:3px 6px 6px;font-weight:600;font-size:11px}#choices{max-height:170px;overflow:auto;overscroll-behavior:contain;scrollbar-width:thin}#choices button,#refresh{display:flex;width:100%;align-items:center;gap:8px;text-align:left;border-radius:5px;min-height:31px;padding:6px;font-size:11px;white-space:normal}.choice-label{flex:1;overflow-wrap:anywhere}.choice-mark{width:12px;flex:none;font-size:12px;color:var(--accent);opacity:0}button[aria-checked=true] .choice-mark{opacity:1}.hint{font-size:10px;font-weight:400;color:var(--muted)}#refresh{color:var(--muted);margin-top:4px;border-top:1px solid var(--border);border-radius:0}
@media(max-width:360px){#toolbar{padding:5px 4px;gap:1px}.control{padding:0 7px}#clock{min-width:57px;padding-right:4px;gap:5px}.divider{margin:0 1px}#stop-label{display:none}}
@keyframes arrive{from{opacity:0;transform:translateY(-5px)}to{opacity:1;transform:translateY(0)}}@keyframes breathe{50%{opacity:.4}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important}}
</style></head><body><section id="recorder" aria-label="Browser recording controls" data-status="starting">
<div id="toolbar" role="toolbar" aria-label="Recording"><div id="clock" title="Recording duration"><span id="indicator" aria-hidden="true"></span><span id="duration">0:00</span></div>
<button id="pause" class="control" data-action="pause" aria-label="Pause recording" title="Pause recording" disabled><span id="pause-mark" aria-hidden="true"></span></button>
<button id="stop" class="control" data-command="stop" title="Stop and save recording" aria-label="Stop and save recording" disabled><span id="stop-mark" aria-hidden="true"></span><span id="stop-label">Stop</span></button>
<span class="divider" aria-hidden="true"></span><button id="microphone" class="control" aria-haspopup="menu" aria-expanded="false" disabled>Mic<span class="chevron" aria-hidden="true"></span></button>
<button id="audio" class="control" aria-haspopup="menu" aria-expanded="false" disabled>Audio<span class="chevron" aria-hidden="true"></span></button><span class="spacer"></span>
<button id="dismiss" class="control" data-command="dismiss" aria-label="Dismiss recording controls" title="Dismiss" hidden>Close</button></div>
<p id="message" role="status" hidden></p><div id="saved-actions" hidden><button id="view" class="control" data-command="show-artifact">View recording</button><button id="save-copy" class="control" data-command="save-copy">Save copy</button></div>
<div id="menu" hidden><p id="menu-title"></p><div id="choices" role="menu"></div><button id="refresh" data-command="refresh-devices">Refresh microphones</button></div>
</section><script nonce="${nonce}">(${mountBrowserRecordingOverlay.toString()})();</script></body></html>`
}
