import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { UploadStore } from '../src/uploads.mjs';
const params = bytes => ({ uploadId: randomUUID(), name: 'photo.png', size: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') });
test('uploads resume after restart, verify repeated ranges, isolate devices/chats and finalize by hash', async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'zyra-upload-')); t.after(() => rmSync(dir, {recursive: true, force: true}));
  const data = Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]), Buffer.alloc(60000, 3)]), input = params(data);
  let store = new UploadStore(dir);
  assert.equal((await store.begin('phone', 'chat', input)).offset, 0);
  const part = data.subarray(0, 48000), chunk = { uploadId: input.uploadId, offset: 0, base64: part.toString('base64') };
  assert.equal((await store.chunk('phone', 'chat', chunk)).offset, part.length);
  assert.equal((await store.chunk('phone', 'chat', chunk)).offset, part.length, 'lost acknowledgements cannot duplicate bytes');
  await assert.rejects(store.chunk('phone', 'chat', { ...chunk, base64: Buffer.alloc(part.length).toString('base64') }), /do not match/);
  store = new UploadStore(dir);
  assert.equal((await store.begin('phone', 'chat', input)).offset, part.length);
  await assert.rejects(store.status('other', 'chat', input.uploadId), /another device/);
  await assert.rejects(store.status('phone', 'other', input.uploadId), /another device/);
  await assert.rejects(store.finish('phone', 'chat', input.uploadId), /Finish uploading/);
  await store.chunk('phone', 'chat', { uploadId: input.uploadId, offset: part.length, base64: data.subarray(part.length).toString('base64') });
  const ready = await store.finish('phone', 'chat', input.uploadId); assert.equal(ready.mimeType, 'image/png'); assert.equal(ready.ready, true);
  assert.equal((await store.images('phone', 'chat', [input.uploadId]))[0].data, data.toString('base64'));
});
test('quota, checksum failure, partial writes and orphan cleanup preserve a bounded resumable store', async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'zyra-upload-budget-')); t.after(() => rmSync(dir, {recursive: true, force: true}));
  let now = 1000; const store = new UploadStore(dir, { now: () => now, quota: 1000 });
  const data = Buffer.alloc(800, 1), input = params(data); await store.begin('phone', 'chat', input);
  await assert.rejects(store.begin('phone', 'chat', params(Buffer.alloc(300))), /storage is full/);
  writeFileSync(store.paths(input.uploadId).bytes, data.subarray(0, 20));
  await store.chunk('phone', 'chat', {uploadId: input.uploadId, offset: 0, base64: data.toString('base64')});
  assert.equal((await store.status('phone', 'chat', input.uploadId)).offset, 800);
  writeFileSync(store.paths(input.uploadId).bytes, Buffer.alloc(800, 2));
  await assert.rejects(store.finish('phone', 'chat', input.uploadId), /checksum failed/);
  now += 24 * 60 * 60 * 1000 + 1;
  assert.equal((await store.begin('phone', 'chat', input)).offset, 0, 'expired partial data is removed before reusing an identifier');
  const orphan = randomUUID(); writeFileSync(store.paths(orphan).bytes, 'unfinished begin'); await store.inventory();
  assert.equal((await store.status('phone', 'chat', input.uploadId)).offset, 0);
});
