import { AMAZON_BEDROCK_MODELS } from "./providers/amazon-bedrock.models.js";
import { ANT_LING_MODELS } from "./providers/ant-ling.models.js";
import { ANTHROPIC_MODELS } from "./providers/anthropic.models.js";
import { AZURE_OPENAI_RESPONSES_MODELS } from "./providers/azure-openai-responses.models.js";
import { BASETEN_MODELS } from "./providers/baseten.models.js";
import { CEREBRAS_MODELS } from "./providers/cerebras.models.js";
import { CLOUDFLARE_AI_GATEWAY_MODELS } from "./providers/cloudflare-ai-gateway.models.js";
import { CLOUDFLARE_WORKERS_AI_MODELS } from "./providers/cloudflare-workers-ai.models.js";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.js";
import { FIREWORKS_MODELS } from "./providers/fireworks.models.js";
import { GITHUB_COPILOT_MODELS } from "./providers/github-copilot.models.js";
import { GOOGLE_MODELS } from "./providers/google.models.js";
import { GOOGLE_VERTEX_MODELS } from "./providers/google-vertex.models.js";
import { GROQ_MODELS } from "./providers/groq.models.js";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.js";
import { KIMI_CODING_MODELS } from "./providers/kimi-coding.models.js";
import { MINIMAX_MODELS } from "./providers/minimax.models.js";
import { MINIMAX_CN_MODELS } from "./providers/minimax-cn.models.js";
import { MISTRAL_MODELS } from "./providers/mistral.models.js";
import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.js";
import { MOONSHOTAI_CN_MODELS } from "./providers/moonshotai-cn.models.js";
import { NVIDIA_MODELS } from "./providers/nvidia.models.js";
import { OPENAI_MODELS } from "./providers/openai.models.js";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.js";
import { OPENCODE_MODELS } from "./providers/opencode.models.js";
import { OPENCODE_GO_MODELS } from "./providers/opencode-go.models.js";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.js";
import { QWEN_TOKEN_PLAN_MODELS } from "./providers/qwen-token-plan.models.js";
import { QWEN_TOKEN_PLAN_CN_MODELS } from "./providers/qwen-token-plan-cn.models.js";
import { QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS } from "./providers/qwen-token-plan-individual.models.js";
import { TOGETHER_MODELS } from "./providers/together.models.js";
import { VERCEL_AI_GATEWAY_MODELS } from "./providers/vercel-ai-gateway.models.js";
import { XAI_MODELS } from "./providers/xai.models.js";
import { XIAOMI_MODELS } from "./providers/xiaomi.models.js";
import { XIAOMI_TOKEN_PLAN_AMS_MODELS } from "./providers/xiaomi-token-plan-ams.models.js";
import { XIAOMI_TOKEN_PLAN_CN_MODELS } from "./providers/xiaomi-token-plan-cn.models.js";
import { XIAOMI_TOKEN_PLAN_SGP_MODELS } from "./providers/xiaomi-token-plan-sgp.models.js";
import { ZAI_MODELS } from "./providers/zai.models.js";
import { ZAI_CODING_CN_MODELS } from "./providers/zai-coding-cn.models.js";
export declare const MODELS: {
    readonly "amazon-bedrock": typeof AMAZON_BEDROCK_MODELS;
    readonly "ant-ling": typeof ANT_LING_MODELS;
    readonly "anthropic": typeof ANTHROPIC_MODELS;
    readonly "azure-openai-responses": typeof AZURE_OPENAI_RESPONSES_MODELS;
    readonly "baseten": typeof BASETEN_MODELS;
    readonly "cerebras": typeof CEREBRAS_MODELS;
    readonly "cloudflare-ai-gateway": typeof CLOUDFLARE_AI_GATEWAY_MODELS;
    readonly "cloudflare-workers-ai": typeof CLOUDFLARE_WORKERS_AI_MODELS;
    readonly "deepseek": typeof DEEPSEEK_MODELS;
    readonly "fireworks": typeof FIREWORKS_MODELS;
    readonly "github-copilot": typeof GITHUB_COPILOT_MODELS;
    readonly "google": typeof GOOGLE_MODELS;
    readonly "google-vertex": typeof GOOGLE_VERTEX_MODELS;
    readonly "groq": typeof GROQ_MODELS;
    readonly "huggingface": typeof HUGGINGFACE_MODELS;
    readonly "kimi-coding": typeof KIMI_CODING_MODELS;
    readonly "minimax": typeof MINIMAX_MODELS;
    readonly "minimax-cn": typeof MINIMAX_CN_MODELS;
    readonly "mistral": typeof MISTRAL_MODELS;
    readonly "moonshotai": typeof MOONSHOTAI_MODELS;
    readonly "moonshotai-cn": typeof MOONSHOTAI_CN_MODELS;
    readonly "nvidia": typeof NVIDIA_MODELS;
    readonly "openai": typeof OPENAI_MODELS;
    readonly "openai-codex": typeof OPENAI_CODEX_MODELS;
    readonly "opencode": typeof OPENCODE_MODELS;
    readonly "opencode-go": typeof OPENCODE_GO_MODELS;
    readonly "openrouter": typeof OPENROUTER_MODELS;
    readonly "qwen-token-plan": typeof QWEN_TOKEN_PLAN_MODELS;
    readonly "qwen-token-plan-cn": typeof QWEN_TOKEN_PLAN_CN_MODELS;
    readonly "qwen-token-plan-individual": typeof QWEN_TOKEN_PLAN_INDIVIDUAL_MODELS;
    readonly "together": typeof TOGETHER_MODELS;
    readonly "vercel-ai-gateway": typeof VERCEL_AI_GATEWAY_MODELS;
    readonly "xai": typeof XAI_MODELS;
    readonly "xiaomi": typeof XIAOMI_MODELS;
    readonly "xiaomi-token-plan-ams": typeof XIAOMI_TOKEN_PLAN_AMS_MODELS;
    readonly "xiaomi-token-plan-cn": typeof XIAOMI_TOKEN_PLAN_CN_MODELS;
    readonly "xiaomi-token-plan-sgp": typeof XIAOMI_TOKEN_PLAN_SGP_MODELS;
    readonly "zai": typeof ZAI_MODELS;
    readonly "zai-coding-cn": typeof ZAI_CODING_CN_MODELS;
};
